---

sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
    - ANSIBLE_VERSION_SPEC="ansible>=1.9,<2.0"
    - ANSIBLE_VERSION_SPEC="ansible>=2.0,<2.1"
    - ANSIBLE_VERSION_SPEC="ansible>=2.1,<2.2"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo apt-get install -y sshpass software-properties-common
  - pip install $ANSIBLE_VERSION_SPEC
  - pip install docker-py
  - ansible --version

script:
  - ansible-playbook -i tests/inventory tests/main.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/main.yml -vv
