---

- name: initialize default variables
  set_fact:
    scm_url: '{{scm_url|mandatory}}'
    scm_target_user: '{{scm_target_user|default(ansible_ssh_user,true)}}'
    scm_target_path: '{{scm_target_path|default("~/src",true)}}'

- name: install system package for scm client
  action:
    module: '{{ansible_pkg_mgr}}'
    name: '{{scm_packages[ansible_pkg_mgr][scm_type]}}'
    state: present
  when: 'scm_packages[ansible_pkg_mgr][scm_type] is defined'

- name: create user for scm checkout
  user: 
    name: '{{scm_target_user}}'
    home: '{{scm_target_user_home|default(omit,true)}}'
    state: present
  when: scm_target_user != ansible_ssh_user

- name: run included tasks with sudo depending on scm_target_user
  include: 'with{% if scm_target_user == ansible_ssh_user %}out{% endif %_sudo.yml'
