---

- name: delete scm target path before update
  file:
    path: "{{ _scm_target_path }}"
    state: absent
  when: scm_delete_on_update | default(false)

- name: create scm target path if needed
  file:
    path: "{{ _scm_target_path }}"
    state: directory
  when: scm_type == 'git' or scm_type == 'hg'

- name: update using git
  git:
    dest: "{{ _scm_target_path }}"
    repo: "{{ _scm_url }}"
    version: "{{ scm_version | default(omit, true) }}"
    force: "{{ scm_force | bool }}"
    accept_hostkey: "{{ scm_accept_hostkey | bool }}"
    depth: "{{ scm_depth | default(omit, true) }}"
    executable: "{{ scm_executable | default(omit, true) }}"
    key_file: "{{ scm_key_file | default(omit, true) }}"
    remote: "{{ scm_remote | default(omit, true) }}"
    track_submodules: "{{ scm_track_submodules | default(omit, true) }}"
    update: "{{ scm_update | default(omit, true) }}"
    verify_commit: "{{ scm_verify_commit | default(omit, true) }}"
  when: scm_type == 'git'
  register: _scm_update_result_git
  notify: "{{ scm_notify_on_updated | default('scm updated', true) }}"

- name: set scm update result fact for git
  set_fact:
    scm_update_result: "{{ _scm_update_result_git }}"
  when: scm_type == 'git'

- name: update using hg
  hg:
    dest: "{{ _scm_target_path }}"
    repo: "{{ _scm_url }}"
    revision: "{{ scm_version | default(omit, true) }}"
    force: "{{ scm_force | bool }}"
    executable: "{{ scm_executable | default(omit, true) }}"
    purge: "{{ scm_purge | default(omit, true) }}"
    update: "{{ scm_update | default(omit, true) }}"
  when: scm_type == 'hg'
  register: _scm_update_result_hg
  notify: "{{ scm_notify_on_updated | default('scm updated', true) }}"

- name: set scm update result fact for hg
  set_fact:
    scm_update_result: "{{ _scm_update_result_hg }}"
  when: scm_type == 'hg'

- name: update using svn
  subversion:
    dest: "{{ _scm_target_path }}"
    repo: "{{ _scm_url }}"
    revision: "{{ scm_version | default(omit, true) }}"
    force: "{{ scm_force | bool }}"
    username: "{{ scm_username | default(omit, true) }}"
    password: "{{ scm_password | default(omit, true) }}"
    executable: "{{ scm_executable | default(omit, true) }}"
    export: "{{ scm_export | default(omit, true) }}"
    switch: "{{ scm_switch | default(omit, true) }}"
    update: "{{ scm_update | default(omit, true) }}"
  when: scm_type == 'svn'
  register: _scm_update_result_svn
  notify: "{{ scm_notify_on_updated | default('scm updated', true) }}"

- name: set scm update result fact for svn
  set_fact:
    scm_update_result: "{{ _scm_update_result_svn }}"
  when: scm_type == 'svn'

- name: apply file and directory permission changes after checkout
  file:
    path: "{{ item.path | default(item) }}"
    state: "{{ item.state | default('directory') }}"
    src: "{{ item.src | default(omit) }}"
    owner: "{{ item.owner | default(_scm_target_user) }}"
    group: "{{ item.group | default(_scm_target_user) }}"
    mode: "{{ item.mode | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    follow: "{{ item.follow | default(omit) }}"
    attributes: "{{ item.attributes | default(omit) }}"
    recurse: "{{ item.recurse | default(omit) }}"
  with_items: "{{ scm_post_checkout_mods }}"
