---

- name: delete scm target path before update
  file:
    path: '{{_scm_target_path}}'
    state: absent
  when: scm_delete_on_update|default(false)

- name: create scm target path if needed
  file:
    path: '{{_scm_target_path}}'
    state: directory
  when: scm_type == 'git' or scm_type == 'hg'

- name: update using git
  git:
    dest: '{{_scm_target_path}}'
    repo: '{{_scm_url}}'
    version: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
    accept_hostkey: '{{scm_accept_hostkey|bool}}'
  when: scm_type == 'git'
  register: scm_update_result_git
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'

- name: set scm update result fact for git
  set_fact:
    scm_update_result: '{{scm_update_result_git}}'
  when: scm_type == 'git'

- name: update using hg
  hg:
    dest: '{{_scm_target_path}}'
    repo: '{{_scm_url}}'
    revision: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
  when: scm_type == 'hg'
  register: scm_update_result_hg
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'

- name: set scm update result fact for hg
  set_fact:
    scm_update_result: '{{scm_update_result_hg}}'
  when: scm_type == 'hg'

- name: update using svn
  subversion:
    dest: '{{_scm_target_path}}'
    repo: '{{_scm_url}}'
    revision: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
    username: '{{scm_username|default(omit,true)}}'
    password: '{{scm_password|default(omit,true)}}'
  when: scm_type == 'svn'
  register: scm_update_result_svn
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'

- name: set scm update result fact for svn
  set_fact:
    scm_update_result: '{{scm_update_result_svn}}'
  when: scm_type == 'svn'
