---

- name: delete scm target path before update with sudo
  file:
    path: '{{scm_target_path}}'
    state: absent
  when: scm_delete_on_update|default(false)
  sudo: yes
  sudo_user: '{{scm_target_user}}'

- name: update using git with sudo
  git:
    dest: '{{scm_target_path}}'
    repo: '{{scm_url}}'
    version: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
    accept_hostkey: '{{scm_accept_hostkey|bool}}'
  when: scm_type == 'git'
  sudo: yes
  sudo_user: '{{scm_target_user}}'
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'

- name: update using hg with sudo
  hg:
    dest: '{{scm_target_path}}'
    repo: '{{scm_url}}'
    revision: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
  when: scm_type == 'hg'
  sudo: yes
  sudo_user: '{{scm_target_user}}'
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'

- name: update using svn with sudo
  subversion:
    dest: '{{scm_target_path}}'
    repo: '{{scm_url}}'
    revision: '{{scm_version|default(omit,true)}}'
    force: '{{scm_force|bool}}'
    username: '{{scm_username|default(omit,true)}}'
    password: '{{scm_password|default(omit,true)}}'
  when: scm_type == 'svn'
  sudo: yes
  sudo_user: '{{scm_target_user}}'
  notify: '{{scm_notify_on_updated|default("scm default handler",true)}}'
